use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InstructionFormat {
    Format10x,
    Format12x,
    Format11n,
    Format11x,
    Format10t,
    Format20t,
    Format30t,
    Format21c,
    Format21s,
    Format21t,
    Format21ih,
    Format21lh,
    Format22c,
    Format22cs,
    Format22s,
    Format22b,
    Format22t,
    Format22x,
    Format23x,
    Format31c,
    Format31i,
    Format31t,
    Format32x,
    Format35c,
    Format35mi,
    Format35ms,
    Format3rc,
    Format3rmi,
    Format3rms,
    Format45cc,
    Format4rcc,
    Format51l,
    Format20bc,
    PackedSwitchPayload,
    SparseSwitchPayload,
    ArrayPayload,
}

impl InstructionFormat {
    pub fn code_units(self) -> u32 {
        match self {
            Self::Format10x => 1,
            Self::Format12x => 1,
            Self::Format11n => 1,
            Self::Format11x => 1,
            Self::Format10t => 1,
            Self::Format20t => 2,
            Self::Format30t => 3,
            Self::Format21c => 2,
            Self::Format21s => 2,
            Self::Format21t => 2,
            Self::Format21ih => 2,
            Self::Format21lh => 2,
            Self::Format22c => 2,
            Self::Format22cs => 2,
            Self::Format22s => 2,
            Self::Format22b => 2,
            Self::Format22t => 2,
            Self::Format22x => 2,
            Self::Format23x => 2,
            Self::Format31c => 3,
            Self::Format31i => 3,
            Self::Format31t => 3,
            Self::Format32x => 2,
            Self::Format35c => 3,
            Self::Format35mi => 3,
            Self::Format35ms => 3,
            Self::Format3rc => 3,
            Self::Format3rmi => 3,
            Self::Format3rms => 3,
            Self::Format45cc => 4,
            Self::Format4rcc => 4,
            Self::Format51l => 5,
            Self::Format20bc => 2,
            Self::PackedSwitchPayload => 0,
            Self::SparseSwitchPayload => 0,
            Self::ArrayPayload => 0,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ReferenceType {
    None,
    String,
    Type,
    Field,
    Method,
    MethodProto,
    CallSite,
    MethodHandle,
}

bitflags::bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct OpcodeFlags: u32 {
        const CAN_THROW = 0x1;
        const ODEX_ONLY = 0x2;
        const CAN_CONTINUE = 0x4;
        const SETS_RESULT = 0x8;
        const SETS_REGISTER = 0x10;
        const SETS_WIDE_REGISTER = 0x20;
        const QUICK_FIELD_ACCESSOR = 0x40;
        const VOLATILE_FIELD_ACCESSOR = 0x80;
        const STATIC_FIELD_ACCESSOR = 0x100;
        const JUMBO_OPCODE = 0x200;
        const CAN_INITIALIZE_REFERENCE = 0x400;
    }
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Opcode {
    Nop = 0x00,
    Move = 0x01,
    MoveFrom16 = 0x02,
    Move16 = 0x03,
    MoveWide = 0x04,
    MoveWideFrom16 = 0x05,
    MoveWide16 = 0x06,
    MoveObject = 0x07,
    MoveObjectFrom16 = 0x08,
    MoveObject16 = 0x09,
    MoveResult = 0x0a,
    MoveResultWide = 0x0b,
    MoveResultObject = 0x0c,
    MoveException = 0x0d,
    ReturnVoid = 0x0e,
    Return = 0x0f,
    ReturnWide = 0x10,
    ReturnObject = 0x11,
    Const4 = 0x12,
    Const16 = 0x13,
    Const = 0x14,
    ConstHigh16 = 0x15,
    ConstWide16 = 0x16,
    ConstWide32 = 0x17,
    ConstWide = 0x18,
    ConstWideHigh16 = 0x19,
    ConstString = 0x1a,
    ConstStringJumbo = 0x1b,
    ConstClass = 0x1c,
    MonitorEnter = 0x1d,
    MonitorExit = 0x1e,
    CheckCast = 0x1f,
    InstanceOf = 0x20,
    ArrayLength = 0x21,
    NewInstance = 0x22,
    NewArray = 0x23,
    FilledNewArray = 0x24,
    FilledNewArrayRange = 0x25,
    FillArrayData = 0x26,
    Throw = 0x27,
    Goto = 0x28,
    Goto16 = 0x29,
    Goto32 = 0x2a,
    PackedSwitch = 0x2b,
    SparseSwitch = 0x2c,
    CmplFloat = 0x2d,
    CmpgFloat = 0x2e,
    CmplDouble = 0x2f,
    CmpgDouble = 0x30,
    CmpLong = 0x31,
    IfEq = 0x32,
    IfNe = 0x33,
    IfLt = 0x34,
    IfGe = 0x35,
    IfGt = 0x36,
    IfLe = 0x37,
    IfEqz = 0x38,
    IfNez = 0x39,
    IfLtz = 0x3a,
    IfGez = 0x3b,
    IfGtz = 0x3c,
    IfLez = 0x3d,
    Aget = 0x44,
    AgetWide = 0x45,
    AgetObject = 0x46,
    AgetBoolean = 0x47,
    AgetByte = 0x48,
    AgetChar = 0x49,
    AgetShort = 0x4a,
    Aput = 0x4b,
    AputWide = 0x4c,
    AputObject = 0x4d,
    AputBoolean = 0x4e,
    AputByte = 0x4f,
    AputChar = 0x50,
    AputShort = 0x51,
    Iget = 0x52,
    IgetWide = 0x53,
    IgetObject = 0x54,
    IgetBoolean = 0x55,
    IgetByte = 0x56,
    IgetChar = 0x57,
    IgetShort = 0x58,
    Iput = 0x59,
    IputWide = 0x5a,
    IputObject = 0x5b,
    IputBoolean = 0x5c,
    IputByte = 0x5d,
    IputChar = 0x5e,
    IputShort = 0x5f,
    Sget = 0x60,
    SgetWide = 0x61,
    SgetObject = 0x62,
    SgetBoolean = 0x63,
    SgetByte = 0x64,
    SgetChar = 0x65,
    SgetShort = 0x66,
    Sput = 0x67,
    SputWide = 0x68,
    SputObject = 0x69,
    SputBoolean = 0x6a,
    SputByte = 0x6b,
    SputChar = 0x6c,
    SputShort = 0x6d,
    InvokeVirtual = 0x6e,
    InvokeSuper = 0x6f,
    InvokeDirect = 0x70,
    InvokeStatic = 0x71,
    InvokeInterface = 0x72,
    InvokeVirtualRange = 0x74,
    InvokeSuperRange = 0x75,
    InvokeDirectRange = 0x76,
    InvokeStaticRange = 0x77,
    InvokeInterfaceRange = 0x78,
    NegInt = 0x7b,
    NotInt = 0x7c,
    NegLong = 0x7d,
    NotLong = 0x7e,
    NegFloat = 0x7f,
    NegDouble = 0x80,
    IntToLong = 0x81,
    IntToFloat = 0x82,
    IntToDouble = 0x83,
    LongToInt = 0x84,
    LongToFloat = 0x85,
    LongToDouble = 0x86,
    FloatToInt = 0x87,
    FloatToLong = 0x88,
    FloatToDouble = 0x89,
    DoubleToInt = 0x8a,
    DoubleToLong = 0x8b,
    DoubleToFloat = 0x8c,
    IntToByte = 0x8d,
    IntToChar = 0x8e,
    IntToShort = 0x8f,
    AddInt = 0x90,
    SubInt = 0x91,
    MulInt = 0x92,
    DivInt = 0x93,
    RemInt = 0x94,
    AndInt = 0x95,
    OrInt = 0x96,
    XorInt = 0x97,
    ShlInt = 0x98,
    ShrInt = 0x99,
    UshrInt = 0x9a,
    AddLong = 0x9b,
    SubLong = 0x9c,
    MulLong = 0x9d,
    DivLong = 0x9e,
    RemLong = 0x9f,
    AndLong = 0xa0,
    OrLong = 0xa1,
    XorLong = 0xa2,
    ShlLong = 0xa3,
    ShrLong = 0xa4,
    UshrLong = 0xa5,
    AddFloat = 0xa6,
    SubFloat = 0xa7,
    MulFloat = 0xa8,
    DivFloat = 0xa9,
    RemFloat = 0xaa,
    AddDouble = 0xab,
    SubDouble = 0xac,
    MulDouble = 0xad,
    DivDouble = 0xae,
    RemDouble = 0xaf,
    AddInt2addr = 0xb0,
    SubInt2addr = 0xb1,
    MulInt2addr = 0xb2,
    DivInt2addr = 0xb3,
    RemInt2addr = 0xb4,
    AndInt2addr = 0xb5,
    OrInt2addr = 0xb6,
    XorInt2addr = 0xb7,
    ShlInt2addr = 0xb8,
    ShrInt2addr = 0xb9,
    UshrInt2addr = 0xba,
    AddLong2addr = 0xbb,
    SubLong2addr = 0xbc,
    MulLong2addr = 0xbd,
    DivLong2addr = 0xbe,
    RemLong2addr = 0xbf,
    AndLong2addr = 0xc0,
    OrLong2addr = 0xc1,
    XorLong2addr = 0xc2,
    ShlLong2addr = 0xc3,
    ShrLong2addr = 0xc4,
    UshrLong2addr = 0xc5,
    AddFloat2addr = 0xc6,
    SubFloat2addr = 0xc7,
    MulFloat2addr = 0xc8,
    DivFloat2addr = 0xc9,
    RemFloat2addr = 0xca,
    AddDouble2addr = 0xcb,
    SubDouble2addr = 0xcc,
    MulDouble2addr = 0xcd,
    DivDouble2addr = 0xce,
    RemDouble2addr = 0xcf,
    AddIntLit16 = 0xd0,
    RsubInt = 0xd1,
    MulIntLit16 = 0xd2,
    DivIntLit16 = 0xd3,
    RemIntLit16 = 0xd4,
    AndIntLit16 = 0xd5,
    OrIntLit16 = 0xd6,
    XorIntLit16 = 0xd7,
    AddIntLit8 = 0xd8,
    RsubIntLit8 = 0xd9,
    MulIntLit8 = 0xda,
    DivIntLit8 = 0xdb,
    RemIntLit8 = 0xdc,
    AndIntLit8 = 0xdd,
    OrIntLit8 = 0xde,
    XorIntLit8 = 0xdf,
    ShlIntLit8 = 0xe0,
    ShrIntLit8 = 0xe1,
    UshrIntLit8 = 0xe2,
    IgetVolatile = 0xe3,
    IputVolatile = 0xe4,
    SgetVolatile = 0xe5,
    SputVolatile = 0xe6,
    IgetObjectVolatile = 0xe7,
    IgetWideVolatile = 0xe8,
    IputWideVolatile = 0xe9,
    SgetWideVolatile = 0xea,
    SputWideVolatile = 0xeb,
    ThrowVerificationError = 0xed,
    ExecuteInline = 0xee,
    ExecuteInlineRange = 0xef,
    InvokeDirectEmpty = 0xf0,
    ReturnVoidBarrier = 0xf1,
    IgetQuick = 0xf2,
    IgetWideQuick = 0xf3,
    IgetObjectQuick = 0xf4,
    IputQuick = 0xf5,
    IputWideQuick = 0xf6,
    IputObjectQuick = 0xf7,
    InvokeVirtualQuick = 0xf8,
    InvokeVirtualQuickRange = 0xf9,
    InvokeSuperQuick = 0xfa,
    InvokeSuperQuickRange = 0xfb,
    IputObjectVolatile = 0xfc,
    SgetObjectVolatile = 0xfd,
    SputObjectVolatile = 0xfe,
    ConstMethodType = 0xff,
}

impl Opcode {
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0x00 => Some(Self::Nop),
            0x01 => Some(Self::Move),
            0x02 => Some(Self::MoveFrom16),
            0x03 => Some(Self::Move16),
            0x04 => Some(Self::MoveWide),
            0x05 => Some(Self::MoveWideFrom16),
            0x06 => Some(Self::MoveWide16),
            0x07 => Some(Self::MoveObject),
            0x08 => Some(Self::MoveObjectFrom16),
            0x09 => Some(Self::MoveObject16),
            0x0a => Some(Self::MoveResult),
            0x0b => Some(Self::MoveResultWide),
            0x0c => Some(Self::MoveResultObject),
            0x0d => Some(Self::MoveException),
            0x0e => Some(Self::ReturnVoid),
            0x0f => Some(Self::Return),
            0x10 => Some(Self::ReturnWide),
            0x11 => Some(Self::ReturnObject),
            0x12 => Some(Self::Const4),
            0x13 => Some(Self::Const16),
            0x14 => Some(Self::Const),
            0x15 => Some(Self::ConstHigh16),
            0x16 => Some(Self::ConstWide16),
            0x17 => Some(Self::ConstWide32),
            0x18 => Some(Self::ConstWide),
            0x19 => Some(Self::ConstWideHigh16),
            0x1a => Some(Self::ConstString),
            0x1b => Some(Self::ConstStringJumbo),
            0x1c => Some(Self::ConstClass),
            0x1d => Some(Self::MonitorEnter),
            0x1e => Some(Self::MonitorExit),
            0x1f => Some(Self::CheckCast),
            0x20 => Some(Self::InstanceOf),
            0x21 => Some(Self::ArrayLength),
            0x22 => Some(Self::NewInstance),
            0x23 => Some(Self::NewArray),
            0x24 => Some(Self::FilledNewArray),
            0x25 => Some(Self::FilledNewArrayRange),
            0x26 => Some(Self::FillArrayData),
            0x27 => Some(Self::Throw),
            0x28 => Some(Self::Goto),
            0x29 => Some(Self::Goto16),
            0x2a => Some(Self::Goto32),
            0x2b => Some(Self::PackedSwitch),
            0x2c => Some(Self::SparseSwitch),
            0x2d => Some(Self::CmplFloat),
            0x2e => Some(Self::CmpgFloat),
            0x2f => Some(Self::CmplDouble),
            0x30 => Some(Self::CmpgDouble),
            0x31 => Some(Self::CmpLong),
            0x32 => Some(Self::IfEq),
            0x33 => Some(Self::IfNe),
            0x34 => Some(Self::IfLt),
            0x35 => Some(Self::IfGe),
            0x36 => Some(Self::IfGt),
            0x37 => Some(Self::IfLe),
            0x38 => Some(Self::IfEqz),
            0x39 => Some(Self::IfNez),
            0x3a => Some(Self::IfLtz),
            0x3b => Some(Self::IfGez),
            0x3c => Some(Self::IfGtz),
            0x3d => Some(Self::IfLez),
            0x44 => Some(Self::Aget),
            0x45 => Some(Self::AgetWide),
            0x46 => Some(Self::AgetObject),
            0x47 => Some(Self::AgetBoolean),
            0x48 => Some(Self::AgetByte),
            0x49 => Some(Self::AgetChar),
            0x4a => Some(Self::AgetShort),
            0x4b => Some(Self::Aput),
            0x4c => Some(Self::AputWide),
            0x4d => Some(Self::AputObject),
            0x4e => Some(Self::AputBoolean),
            0x4f => Some(Self::AputByte),
            0x50 => Some(Self::AputChar),
            0x51 => Some(Self::AputShort),
            0x52 => Some(Self::Iget),
            0x53 => Some(Self::IgetWide),
            0x54 => Some(Self::IgetObject),
            0x55 => Some(Self::IgetBoolean),
            0x56 => Some(Self::IgetByte),
            0x57 => Some(Self::IgetChar),
            0x58 => Some(Self::IgetShort),
            0x59 => Some(Self::Iput),
            0x5a => Some(Self::IputWide),
            0x5b => Some(Self::IputObject),
            0x5c => Some(Self::IputBoolean),
            0x5d => Some(Self::IputByte),
            0x5e => Some(Self::IputChar),
            0x5f => Some(Self::IputShort),
            0x60 => Some(Self::Sget),
            0x61 => Some(Self::SgetWide),
            0x62 => Some(Self::SgetObject),
            0x63 => Some(Self::SgetBoolean),
            0x64 => Some(Self::SgetByte),
            0x65 => Some(Self::SgetChar),
            0x66 => Some(Self::SgetShort),
            0x67 => Some(Self::Sput),
            0x68 => Some(Self::SputWide),
            0x69 => Some(Self::SputObject),
            0x6a => Some(Self::SputBoolean),
            0x6b => Some(Self::SputByte),
            0x6c => Some(Self::SputChar),
            0x6d => Some(Self::SputShort),
            0x6e => Some(Self::InvokeVirtual),
            0x6f => Some(Self::InvokeSuper),
            0x70 => Some(Self::InvokeDirect),
            0x71 => Some(Self::InvokeStatic),
            0x72 => Some(Self::InvokeInterface),
            0x74 => Some(Self::InvokeVirtualRange),
            0x75 => Some(Self::InvokeSuperRange),
            0x76 => Some(Self::InvokeDirectRange),
            0x77 => Some(Self::InvokeStaticRange),
            0x78 => Some(Self::InvokeInterfaceRange),
            0x7b => Some(Self::NegInt),
            0x7c => Some(Self::NotInt),
            0x7d => Some(Self::NegLong),
            0x7e => Some(Self::NotLong),
            0x7f => Some(Self::NegFloat),
            0x80 => Some(Self::NegDouble),
            0x81 => Some(Self::IntToLong),
            0x82 => Some(Self::IntToFloat),
            0x83 => Some(Self::IntToDouble),
            0x84 => Some(Self::LongToInt),
            0x85 => Some(Self::LongToFloat),
            0x86 => Some(Self::LongToDouble),
            0x87 => Some(Self::FloatToInt),
            0x88 => Some(Self::FloatToLong),
            0x89 => Some(Self::FloatToDouble),
            0x8a => Some(Self::DoubleToInt),
            0x8b => Some(Self::DoubleToLong),
            0x8c => Some(Self::DoubleToFloat),
            0x8d => Some(Self::IntToByte),
            0x8e => Some(Self::IntToChar),
            0x8f => Some(Self::IntToShort),
            0x90 => Some(Self::AddInt),
            0x91 => Some(Self::SubInt),
            0x92 => Some(Self::MulInt),
            0x93 => Some(Self::DivInt),
            0x94 => Some(Self::RemInt),
            0x95 => Some(Self::AndInt),
            0x96 => Some(Self::OrInt),
            0x97 => Some(Self::XorInt),
            0x98 => Some(Self::ShlInt),
            0x99 => Some(Self::ShrInt),
            0x9a => Some(Self::UshrInt),
            0x9b => Some(Self::AddLong),
            0x9c => Some(Self::SubLong),
            0x9d => Some(Self::MulLong),
            0x9e => Some(Self::DivLong),
            0x9f => Some(Self::RemLong),
            0xa0 => Some(Self::AndLong),
            0xa1 => Some(Self::OrLong),
            0xa2 => Some(Self::XorLong),
            0xa3 => Some(Self::ShlLong),
            0xa4 => Some(Self::ShrLong),
            0xa5 => Some(Self::UshrLong),
            0xa6 => Some(Self::AddFloat),
            0xa7 => Some(Self::SubFloat),
            0xa8 => Some(Self::MulFloat),
            0xa9 => Some(Self::DivFloat),
            0xaa => Some(Self::RemFloat),
            0xab => Some(Self::AddDouble),
            0xac => Some(Self::SubDouble),
            0xad => Some(Self::MulDouble),
            0xae => Some(Self::DivDouble),
            0xaf => Some(Self::RemDouble),
            0xb0 => Some(Self::AddInt2addr),
            0xb1 => Some(Self::SubInt2addr),
            0xb2 => Some(Self::MulInt2addr),
            0xb3 => Some(Self::DivInt2addr),
            0xb4 => Some(Self::RemInt2addr),
            0xb5 => Some(Self::AndInt2addr),
            0xb6 => Some(Self::OrInt2addr),
            0xb7 => Some(Self::XorInt2addr),
            0xb8 => Some(Self::ShlInt2addr),
            0xb9 => Some(Self::ShrInt2addr),
            0xba => Some(Self::UshrInt2addr),
            0xbb => Some(Self::AddLong2addr),
            0xbc => Some(Self::SubLong2addr),
            0xbd => Some(Self::MulLong2addr),
            0xbe => Some(Self::DivLong2addr),
            0xbf => Some(Self::RemLong2addr),
            0xc0 => Some(Self::AndLong2addr),
            0xc1 => Some(Self::OrLong2addr),
            0xc2 => Some(Self::XorLong2addr),
            0xc3 => Some(Self::ShlLong2addr),
            0xc4 => Some(Self::ShrLong2addr),
            0xc5 => Some(Self::UshrLong2addr),
            0xc6 => Some(Self::AddFloat2addr),
            0xc7 => Some(Self::SubFloat2addr),
            0xc8 => Some(Self::MulFloat2addr),
            0xc9 => Some(Self::DivFloat2addr),
            0xca => Some(Self::RemFloat2addr),
            0xcb => Some(Self::AddDouble2addr),
            0xcc => Some(Self::SubDouble2addr),
            0xcd => Some(Self::MulDouble2addr),
            0xce => Some(Self::DivDouble2addr),
            0xcf => Some(Self::RemDouble2addr),
            0xd0 => Some(Self::AddIntLit16),
            0xd1 => Some(Self::RsubInt),
            0xd2 => Some(Self::MulIntLit16),
            0xd3 => Some(Self::DivIntLit16),
            0xd4 => Some(Self::RemIntLit16),
            0xd5 => Some(Self::AndIntLit16),
            0xd6 => Some(Self::OrIntLit16),
            0xd7 => Some(Self::XorIntLit16),
            0xd8 => Some(Self::AddIntLit8),
            0xd9 => Some(Self::RsubIntLit8),
            0xda => Some(Self::MulIntLit8),
            0xdb => Some(Self::DivIntLit8),
            0xdc => Some(Self::RemIntLit8),
            0xdd => Some(Self::AndIntLit8),
            0xde => Some(Self::OrIntLit8),
            0xdf => Some(Self::XorIntLit8),
            0xe0 => Some(Self::ShlIntLit8),
            0xe1 => Some(Self::ShrIntLit8),
            0xe2 => Some(Self::UshrIntLit8),
            0xe3 => Some(Self::IgetVolatile),
            0xe4 => Some(Self::IputVolatile),
            0xe5 => Some(Self::SgetVolatile),
            0xe6 => Some(Self::SputVolatile),
            0xe7 => Some(Self::IgetObjectVolatile),
            0xe8 => Some(Self::IgetWideVolatile),
            0xe9 => Some(Self::IputWideVolatile),
            0xea => Some(Self::SgetWideVolatile),
            0xeb => Some(Self::SputWideVolatile),
            0xed => Some(Self::ThrowVerificationError),
            0xee => Some(Self::ExecuteInline),
            0xef => Some(Self::ExecuteInlineRange),
            0xf0 => Some(Self::InvokeDirectEmpty),
            0xf1 => Some(Self::ReturnVoidBarrier),
            0xf2 => Some(Self::IgetQuick),
            0xf3 => Some(Self::IgetWideQuick),
            0xf4 => Some(Self::IgetObjectQuick),
            0xf5 => Some(Self::IputQuick),
            0xf6 => Some(Self::IputWideQuick),
            0xf7 => Some(Self::IputObjectQuick),
            0xf8 => Some(Self::InvokeVirtualQuick),
            0xf9 => Some(Self::InvokeVirtualQuickRange),
            0xfa => Some(Self::InvokeSuperQuick),
            0xfb => Some(Self::InvokeSuperQuickRange),
            0xfc => Some(Self::IputObjectVolatile),
            0xfd => Some(Self::SgetObjectVolatile),
            0xfe => Some(Self::SputObjectVolatile),
            0xff => Some(Self::ConstMethodType),
            _ => None,
        }
    }

    pub fn format(self) -> InstructionFormat {
        match self {
            Self::Nop => InstructionFormat::Format10x,
            Self::Move | Self::MoveWide | Self::MoveObject => InstructionFormat::Format12x,
            Self::MoveFrom16 | Self::MoveWideFrom16 | Self::MoveObjectFrom16 => InstructionFormat::Format22x,
            Self::Move16 | Self::MoveWide16 | Self::MoveObject16 => InstructionFormat::Format32x,
            Self::MoveResult | Self::MoveResultWide | Self::MoveResultObject | Self::MoveException => InstructionFormat::Format11x,
            Self::ReturnVoid => InstructionFormat::Format10x,
            Self::Return | Self::ReturnWide | Self::ReturnObject => InstructionFormat::Format11x,
            Self::Const4 => InstructionFormat::Format11n,
            Self::Const16 | Self::ConstWide16 => InstructionFormat::Format21s,
            Self::Const | Self::ConstWide32 => InstructionFormat::Format31i,
            Self::ConstHigh16 => InstructionFormat::Format21ih,
            Self::ConstWide => InstructionFormat::Format51l,
            Self::ConstWideHigh16 => InstructionFormat::Format21lh,
            Self::ConstString => InstructionFormat::Format21c,
            Self::ConstStringJumbo => InstructionFormat::Format31c,
            Self::ConstClass => InstructionFormat::Format21c,
            Self::MonitorEnter | Self::MonitorExit => InstructionFormat::Format11x,
            Self::CheckCast => InstructionFormat::Format21c,
            Self::InstanceOf | Self::NewArray => InstructionFormat::Format22c,
            Self::ArrayLength => InstructionFormat::Format12x,
            Self::NewInstance => InstructionFormat::Format21c,
            Self::FilledNewArray => InstructionFormat::Format35c,
            Self::FilledNewArrayRange => InstructionFormat::Format3rc,
            Self::FillArrayData => InstructionFormat::Format31t,
            Self::Throw => InstructionFormat::Format11x,
            Self::Goto => InstructionFormat::Format10t,
            Self::Goto16 => InstructionFormat::Format20t,
            Self::Goto32 => InstructionFormat::Format30t,
            Self::PackedSwitch | Self::SparseSwitch => InstructionFormat::Format31t,
            Self::CmplFloat | Self::CmpgFloat | Self::CmplDouble | Self::CmpgDouble | Self::CmpLong => InstructionFormat::Format23x,
            Self::IfEq | Self::IfNe | Self::IfLt | Self::IfGe | Self::IfGt | Self::IfLe => InstructionFormat::Format22t,
            Self::IfEqz | Self::IfNez | Self::IfLtz | Self::IfGez | Self::IfGtz | Self::IfLez => InstructionFormat::Format21t,
            Self::Aget | Self::AgetWide | Self::AgetObject | Self::AgetBoolean | Self::AgetByte | Self::AgetChar | Self::AgetShort
            | Self::Aput | Self::AputWide | Self::AputObject | Self::AputBoolean | Self::AputByte | Self::AputChar | Self::AputShort => InstructionFormat::Format23x,
            Self::Iget | Self::IgetWide | Self::IgetObject | Self::IgetBoolean | Self::IgetByte | Self::IgetChar | Self::IgetShort
            | Self::Iput | Self::IputWide | Self::IputObject | Self::IputBoolean | Self::IputByte | Self::IputChar | Self::IputShort => InstructionFormat::Format22c,
            Self::Sget | Self::SgetWide | Self::SgetObject | Self::SgetBoolean | Self::SgetByte | Self::SgetChar | Self::SgetShort
            | Self::Sput | Self::SputWide | Self::SputObject | Self::SputBoolean | Self::SputByte | Self::SputChar | Self::SputShort => InstructionFormat::Format21c,
            Self::InvokeVirtual | Self::InvokeSuper | Self::InvokeDirect | Self::InvokeStatic | Self::InvokeInterface => InstructionFormat::Format35c,
            Self::InvokeVirtualRange | Self::InvokeSuperRange | Self::InvokeDirectRange | Self::InvokeStaticRange | Self::InvokeInterfaceRange => InstructionFormat::Format3rc,
            Self::NegInt | Self::NotInt | Self::NegLong | Self::NotLong | Self::NegFloat | Self::NegDouble
            | Self::IntToLong | Self::IntToFloat | Self::IntToDouble | Self::LongToInt | Self::LongToFloat | Self::LongToDouble
            | Self::FloatToInt | Self::FloatToLong | Self::FloatToDouble | Self::DoubleToInt | Self::DoubleToLong | Self::DoubleToFloat
            | Self::IntToByte | Self::IntToChar | Self::IntToShort => InstructionFormat::Format12x,
            Self::AddInt | Self::SubInt | Self::MulInt | Self::DivInt | Self::RemInt | Self::AndInt | Self::OrInt | Self::XorInt | Self::ShlInt | Self::ShrInt | Self::UshrInt
            | Self::AddLong | Self::SubLong | Self::MulLong | Self::DivLong | Self::RemLong | Self::AndLong | Self::OrLong | Self::XorLong | Self::ShlLong | Self::ShrLong | Self::UshrLong
            | Self::AddFloat | Self::SubFloat | Self::MulFloat | Self::DivFloat | Self::RemFloat
            | Self::AddDouble | Self::SubDouble | Self::MulDouble | Self::DivDouble | Self::RemDouble => InstructionFormat::Format23x,
            Self::AddInt2addr | Self::SubInt2addr | Self::MulInt2addr | Self::DivInt2addr | Self::RemInt2addr | Self::AndInt2addr | Self::OrInt2addr | Self::XorInt2addr | Self::ShlInt2addr | Self::ShrInt2addr | Self::UshrInt2addr
            | Self::AddLong2addr | Self::SubLong2addr | Self::MulLong2addr | Self::DivLong2addr | Self::RemLong2addr | Self::AndLong2addr | Self::OrLong2addr | Self::XorLong2addr | Self::ShlLong2addr | Self::ShrLong2addr | Self::UshrLong2addr
            | Self::AddFloat2addr | Self::SubFloat2addr | Self::MulFloat2addr | Self::DivFloat2addr | Self::RemFloat2addr
            | Self::AddDouble2addr | Self::SubDouble2addr | Self::MulDouble2addr | Self::DivDouble2addr | Self::RemDouble2addr => InstructionFormat::Format12x,
            Self::AddIntLit16 | Self::RsubInt | Self::MulIntLit16 | Self::DivIntLit16 | Self::RemIntLit16 | Self::AndIntLit16 | Self::OrIntLit16 | Self::XorIntLit16 => InstructionFormat::Format22s,
            Self::AddIntLit8 | Self::RsubIntLit8 | Self::MulIntLit8 | Self::DivIntLit8 | Self::RemIntLit8 | Self::AndIntLit8 | Self::OrIntLit8 | Self::XorIntLit8 | Self::ShlIntLit8 | Self::ShrIntLit8 | Self::UshrIntLit8 => InstructionFormat::Format22b,
            Self::IgetVolatile | Self::IputVolatile | Self::IgetObjectVolatile | Self::IgetWideVolatile | Self::IputWideVolatile | Self::IputObjectVolatile => InstructionFormat::Format22c,
            Self::SgetVolatile | Self::SputVolatile | Self::SgetWideVolatile | Self::SputWideVolatile | Self::SgetObjectVolatile | Self::SputObjectVolatile => InstructionFormat::Format21c,
            Self::ThrowVerificationError => InstructionFormat::Format20bc,
            Self::ExecuteInline => InstructionFormat::Format35mi,
            Self::ExecuteInlineRange => InstructionFormat::Format3rmi,
            Self::InvokeDirectEmpty => InstructionFormat::Format35c,
            Self::ReturnVoidBarrier => InstructionFormat::Format10x,
            Self::IgetQuick | Self::IgetWideQuick | Self::IgetObjectQuick | Self::IputQuick | Self::IputWideQuick | Self::IputObjectQuick => InstructionFormat::Format22cs,
            Self::InvokeVirtualQuick | Self::InvokeSuperQuick => InstructionFormat::Format35ms,
            Self::InvokeVirtualQuickRange | Self::InvokeSuperQuickRange => InstructionFormat::Format3rms,
            Self::ConstMethodType => InstructionFormat::Format21c,
        }
    }

    pub fn reference_type(self) -> ReferenceType {
        match self {
            Self::ConstString | Self::ConstStringJumbo => ReferenceType::String,
            Self::ConstClass | Self::CheckCast | Self::NewInstance | Self::NewArray | Self::FilledNewArray | Self::FilledNewArrayRange => ReferenceType::Type,
            Self::Iget | Self::IgetWide | Self::IgetObject | Self::IgetBoolean | Self::IgetByte | Self::IgetChar | Self::IgetShort
            | Self::Iput | Self::IputWide | Self::IputObject | Self::IputBoolean | Self::IputByte | Self::IputChar | Self::IputShort
            | Self::Sget | Self::SgetWide | Self::SgetObject | Self::SgetBoolean | Self::SgetByte | Self::SgetChar | Self::SgetShort
            | Self::Sput | Self::SputWide | Self::SputObject | Self::SputBoolean | Self::SputByte | Self::SputChar | Self::SputShort
            | Self::IgetVolatile | Self::IputVolatile | Self::IgetObjectVolatile | Self::IgetWideVolatile | Self::IputWideVolatile | Self::IputObjectVolatile
            | Self::SgetVolatile | Self::SputVolatile | Self::SgetWideVolatile | Self::SputWideVolatile | Self::SgetObjectVolatile | Self::SputObjectVolatile
            | Self::InstanceOf => ReferenceType::Field,
            Self::InvokeVirtual | Self::InvokeSuper | Self::InvokeDirect | Self::InvokeStatic | Self::InvokeInterface
            | Self::InvokeVirtualRange | Self::InvokeSuperRange | Self::InvokeDirectRange | Self::InvokeStaticRange | Self::InvokeInterfaceRange
            | Self::InvokeDirectEmpty => ReferenceType::Method,
            Self::ConstMethodType => ReferenceType::MethodProto,
            _ => ReferenceType::None,
        }
    }

    pub fn flags(self) -> OpcodeFlags {
        match self {
            Self::Nop => OpcodeFlags::CAN_CONTINUE,
            Self::Move | Self::MoveFrom16 | Self::Move16 | Self::MoveObject | Self::MoveObjectFrom16 | Self::MoveObject16 => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::MoveWide | Self::MoveWideFrom16 | Self::MoveWide16 => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::MoveResult | Self::MoveResultObject | Self::MoveException => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::MoveResultWide => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::ReturnVoid | Self::Return | Self::ReturnWide | Self::ReturnObject => OpcodeFlags::empty(),
            Self::Const4 | Self::Const16 | Self::Const | Self::ConstHigh16 => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::ConstWide16 | Self::ConstWide32 | Self::ConstWideHigh16 => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::ConstWide => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::ConstString | Self::ConstStringJumbo => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::ConstClass => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::MonitorEnter | Self::MonitorExit => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE,
            Self::CheckCast => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::InstanceOf => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::ArrayLength => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::NewInstance => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::NewArray => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::FilledNewArray | Self::FilledNewArrayRange => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_RESULT,
            Self::FillArrayData => OpcodeFlags::CAN_CONTINUE,
            Self::Throw => OpcodeFlags::CAN_THROW,
            Self::Goto | Self::Goto16 | Self::Goto32 => OpcodeFlags::empty(),
            Self::PackedSwitch | Self::SparseSwitch => OpcodeFlags::CAN_CONTINUE,
            Self::CmplFloat | Self::CmpgFloat | Self::CmpLong => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::CmplDouble | Self::CmpgDouble => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::IfEq | Self::IfNe | Self::IfLt | Self::IfGe | Self::IfGt | Self::IfLe => OpcodeFlags::CAN_CONTINUE,
            Self::IfEqz | Self::IfNez | Self::IfLtz | Self::IfGez | Self::IfGtz | Self::IfLez => OpcodeFlags::CAN_CONTINUE,
            Self::Aget | Self::AgetObject | Self::AgetBoolean | Self::AgetByte | Self::AgetChar | Self::AgetShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::AgetWide => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::Aput | Self::AputWide | Self::AputObject | Self::AputBoolean | Self::AputByte | Self::AputChar | Self::AputShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE,
            Self::Iget | Self::IgetObject | Self::IgetBoolean | Self::IgetByte | Self::IgetChar | Self::IgetShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::IgetWide => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::Iput | Self::IputWide | Self::IputObject | Self::IputBoolean | Self::IputByte | Self::IputChar | Self::IputShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE,
            Self::Sget | Self::SgetObject | Self::SgetBoolean | Self::SgetByte | Self::SgetChar | Self::SgetShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::STATIC_FIELD_ACCESSOR,
            Self::SgetWide => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER | OpcodeFlags::STATIC_FIELD_ACCESSOR,
            Self::Sput | Self::SputWide | Self::SputObject | Self::SputBoolean | Self::SputByte | Self::SputChar | Self::SputShort => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::STATIC_FIELD_ACCESSOR,
            Self::InvokeVirtual | Self::InvokeSuper | Self::InvokeStatic | Self::InvokeInterface => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_RESULT,
            Self::InvokeDirect => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_RESULT | OpcodeFlags::CAN_INITIALIZE_REFERENCE,
            Self::InvokeVirtualRange | Self::InvokeSuperRange | Self::InvokeStaticRange | Self::InvokeInterfaceRange => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_RESULT,
            Self::InvokeDirectRange => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_RESULT | OpcodeFlags::CAN_INITIALIZE_REFERENCE,
            Self::NegInt | Self::NotInt | Self::NegFloat => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::NegLong | Self::NotLong | Self::NegDouble => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::IntToLong | Self::IntToFloat | Self::IntToDouble | Self::LongToInt | Self::LongToFloat | Self::FloatToInt | Self::FloatToLong | Self::DoubleToFloat | Self::IntToByte | Self::IntToChar | Self::IntToShort => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::LongToDouble | Self::FloatToDouble | Self::DoubleToInt | Self::DoubleToLong => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::AddInt | Self::SubInt | Self::MulInt | Self::AndInt | Self::OrInt | Self::XorInt | Self::ShlInt | Self::ShrInt | Self::UshrInt
            | Self::AddFloat | Self::SubFloat | Self::MulFloat | Self::DivFloat | Self::RemFloat => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::DivInt | Self::RemInt => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::AddLong | Self::SubLong | Self::MulLong | Self::AndLong | Self::OrLong | Self::XorLong | Self::ShlLong | Self::ShrLong | Self::UshrLong
            | Self::AddDouble | Self::SubDouble | Self::MulDouble | Self::DivDouble | Self::RemDouble => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::DivLong | Self::RemLong => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::AddInt2addr | Self::SubInt2addr | Self::MulInt2addr | Self::AndInt2addr | Self::OrInt2addr | Self::XorInt2addr | Self::ShlInt2addr | Self::ShrInt2addr | Self::UshrInt2addr
            | Self::AddFloat2addr | Self::SubFloat2addr | Self::MulFloat2addr | Self::DivFloat2addr | Self::RemFloat2addr => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::DivInt2addr | Self::RemInt2addr => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::AddLong2addr | Self::SubLong2addr | Self::MulLong2addr | Self::AndLong2addr | Self::OrLong2addr | Self::XorLong2addr | Self::ShlLong2addr | Self::ShrLong2addr | Self::UshrLong2addr
            | Self::AddDouble2addr | Self::SubDouble2addr | Self::MulDouble2addr | Self::DivDouble2addr | Self::RemDouble2addr => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::DivLong2addr | Self::RemLong2addr => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER | OpcodeFlags::SETS_WIDE_REGISTER,
            Self::AddIntLit16 | Self::RsubInt | Self::MulIntLit16 | Self::AndIntLit16 | Self::OrIntLit16 | Self::XorIntLit16
            | Self::AddIntLit8 | Self::RsubIntLit8 | Self::MulIntLit8 | Self::AndIntLit8 | Self::OrIntLit8 | Self::XorIntLit8 | Self::ShlIntLit8 | Self::ShrIntLit8 | Self::UshrIntLit8 => OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            Self::DivIntLit16 | Self::RemIntLit16 | Self::DivIntLit8 | Self::RemIntLit8 => OpcodeFlags::CAN_THROW | OpcodeFlags::CAN_CONTINUE | OpcodeFlags::SETS_REGISTER,
            _ => OpcodeFlags::empty(),
        }
    }

    pub fn can_throw(self) -> bool {
        self.flags().contains(OpcodeFlags::CAN_THROW)
    }

    pub fn can_continue(self) -> bool {
        self.flags().contains(OpcodeFlags::CAN_CONTINUE)
    }

    pub fn sets_register(self) -> bool {
        self.flags().contains(OpcodeFlags::SETS_REGISTER)
    }

    pub fn sets_wide_register(self) -> bool {
        self.flags().contains(OpcodeFlags::SETS_WIDE_REGISTER)
    }

    pub fn code_units(self) -> u32 {
        self.format().code_units()
    }
}

impl fmt::Display for Opcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Self::Nop => "nop",
            Self::Move => "move",
            Self::MoveFrom16 => "move/from16",
            Self::Move16 => "move/16",
            Self::MoveWide => "move-wide",
            Self::MoveWideFrom16 => "move-wide/from16",
            Self::MoveWide16 => "move-wide/16",
            Self::MoveObject => "move-object",
            Self::MoveObjectFrom16 => "move-object/from16",
            Self::MoveObject16 => "move-object/16",
            Self::MoveResult => "move-result",
            Self::MoveResultWide => "move-result-wide",
            Self::MoveResultObject => "move-result-object",
            Self::MoveException => "move-exception",
            Self::ReturnVoid => "return-void",
            Self::Return => "return",
            Self::ReturnWide => "return-wide",
            Self::ReturnObject => "return-object",
            Self::Const4 => "const/4",
            Self::Const16 => "const/16",
            Self::Const => "const",
            Self::ConstHigh16 => "const/high16",
            Self::ConstWide16 => "const-wide/16",
            Self::ConstWide32 => "const-wide/32",
            Self::ConstWide => "const-wide",
            Self::ConstWideHigh16 => "const-wide/high16",
            Self::ConstString => "const-string",
            Self::ConstStringJumbo => "const-string/jumbo",
            Self::ConstClass => "const-class",
            Self::MonitorEnter => "monitor-enter",
            Self::MonitorExit => "monitor-exit",
            Self::CheckCast => "check-cast",
            Self::InstanceOf => "instance-of",
            Self::ArrayLength => "array-length",
            Self::NewInstance => "new-instance",
            Self::NewArray => "new-array",
            Self::FilledNewArray => "filled-new-array",
            Self::FilledNewArrayRange => "filled-new-array/range",
            Self::FillArrayData => "fill-array-data",
            Self::Throw => "throw",
            Self::Goto => "goto",
            Self::Goto16 => "goto/16",
            Self::Goto32 => "goto/32",
            Self::PackedSwitch => "packed-switch",
            Self::SparseSwitch => "sparse-switch",
            Self::CmplFloat => "cmpl-float",
            Self::CmpgFloat => "cmpg-float",
            Self::CmplDouble => "cmpl-double",
            Self::CmpgDouble => "cmpg-double",
            Self::CmpLong => "cmp-long",
            Self::IfEq => "if-eq",
            Self::IfNe => "if-ne",
            Self::IfLt => "if-lt",
            Self::IfGe => "if-ge",
            Self::IfGt => "if-gt",
            Self::IfLe => "if-le",
            Self::IfEqz => "if-eqz",
            Self::IfNez => "if-nez",
            Self::IfLtz => "if-ltz",
            Self::IfGez => "if-gez",
            Self::IfGtz => "if-gtz",
            Self::IfLez => "if-lez",
            Self::Aget => "aget",
            Self::AgetWide => "aget-wide",
            Self::AgetObject => "aget-object",
            Self::AgetBoolean => "aget-boolean",
            Self::AgetByte => "aget-byte",
            Self::AgetChar => "aget-char",
            Self::AgetShort => "aget-short",
            Self::Aput => "aput",
            Self::AputWide => "aput-wide",
            Self::AputObject => "aput-object",
            Self::AputBoolean => "aput-boolean",
            Self::AputByte => "aput-byte",
            Self::AputChar => "aput-char",
            Self::AputShort => "aput-short",
            Self::Iget => "iget",
            Self::IgetWide => "iget-wide",
            Self::IgetObject => "iget-object",
            Self::IgetBoolean => "iget-boolean",
            Self::IgetByte => "iget-byte",
            Self::IgetChar => "iget-char",
            Self::IgetShort => "iget-short",
            Self::Iput => "iput",
            Self::IputWide => "iput-wide",
            Self::IputObject => "iput-object",
            Self::IputBoolean => "iput-boolean",
            Self::IputByte => "iput-byte",
            Self::IputChar => "iput-char",
            Self::IputShort => "iput-short",
            Self::Sget => "sget",
            Self::SgetWide => "sget-wide",
            Self::SgetObject => "sget-object",
            Self::SgetBoolean => "sget-boolean",
            Self::SgetByte => "sget-byte",
            Self::SgetChar => "sget-char",
            Self::SgetShort => "sget-short",
            Self::Sput => "sput",
            Self::SputWide => "sput-wide",
            Self::SputObject => "sput-object",
            Self::SputBoolean => "sput-boolean",
            Self::SputByte => "sput-byte",
            Self::SputChar => "sput-char",
            Self::SputShort => "sput-short",
            Self::InvokeVirtual => "invoke-virtual",
            Self::InvokeSuper => "invoke-super",
            Self::InvokeDirect => "invoke-direct",
            Self::InvokeStatic => "invoke-static",
            Self::InvokeInterface => "invoke-interface",
            Self::InvokeVirtualRange => "invoke-virtual/range",
            Self::InvokeSuperRange => "invoke-super/range",
            Self::InvokeDirectRange => "invoke-direct/range",
            Self::InvokeStaticRange => "invoke-static/range",
            Self::InvokeInterfaceRange => "invoke-interface/range",
            Self::NegInt => "neg-int",
            Self::NotInt => "not-int",
            Self::NegLong => "neg-long",
            Self::NotLong => "not-long",
            Self::NegFloat => "neg-float",
            Self::NegDouble => "neg-double",
            Self::IntToLong => "int-to-long",
            Self::IntToFloat => "int-to-float",
            Self::IntToDouble => "int-to-double",
            Self::LongToInt => "long-to-int",
            Self::LongToFloat => "long-to-float",
            Self::LongToDouble => "long-to-double",
            Self::FloatToInt => "float-to-int",
            Self::FloatToLong => "float-to-long",
            Self::FloatToDouble => "float-to-double",
            Self::DoubleToInt => "double-to-int",
            Self::DoubleToLong => "double-to-long",
            Self::DoubleToFloat => "double-to-float",
            Self::IntToByte => "int-to-byte",
            Self::IntToChar => "int-to-char",
            Self::IntToShort => "int-to-short",
            Self::AddInt => "add-int",
            Self::SubInt => "sub-int",
            Self::MulInt => "mul-int",
            Self::DivInt => "div-int",
            Self::RemInt => "rem-int",
            Self::AndInt => "and-int",
            Self::OrInt => "or-int",
            Self::XorInt => "xor-int",
            Self::ShlInt => "shl-int",
            Self::ShrInt => "shr-int",
            Self::UshrInt => "ushr-int",
            Self::AddLong => "add-long",
            Self::SubLong => "sub-long",
            Self::MulLong => "mul-long",
            Self::DivLong => "div-long",
            Self::RemLong => "rem-long",
            Self::AndLong => "and-long",
            Self::OrLong => "or-long",
            Self::XorLong => "xor-long",
            Self::ShlLong => "shl-long",
            Self::ShrLong => "shr-long",
            Self::UshrLong => "ushr-long",
            Self::AddFloat => "add-float",
            Self::SubFloat => "sub-float",
            Self::MulFloat => "mul-float",
            Self::DivFloat => "div-float",
            Self::RemFloat => "rem-float",
            Self::AddDouble => "add-double",
            Self::SubDouble => "sub-double",
            Self::MulDouble => "mul-double",
            Self::DivDouble => "div-double",
            Self::RemDouble => "rem-double",
            Self::AddInt2addr => "add-int/2addr",
            Self::SubInt2addr => "sub-int/2addr",
            Self::MulInt2addr => "mul-int/2addr",
            Self::DivInt2addr => "div-int/2addr",
            Self::RemInt2addr => "rem-int/2addr",
            Self::AndInt2addr => "and-int/2addr",
            Self::OrInt2addr => "or-int/2addr",
            Self::XorInt2addr => "xor-int/2addr",
            Self::ShlInt2addr => "shl-int/2addr",
            Self::ShrInt2addr => "shr-int/2addr",
            Self::UshrInt2addr => "ushr-int/2addr",
            Self::AddLong2addr => "add-long/2addr",
            Self::SubLong2addr => "sub-long/2addr",
            Self::MulLong2addr => "mul-long/2addr",
            Self::DivLong2addr => "div-long/2addr",
            Self::RemLong2addr => "rem-long/2addr",
            Self::AndLong2addr => "and-long/2addr",
            Self::OrLong2addr => "or-long/2addr",
            Self::XorLong2addr => "xor-long/2addr",
            Self::ShlLong2addr => "shl-long/2addr",
            Self::ShrLong2addr => "shr-long/2addr",
            Self::UshrLong2addr => "ushr-long/2addr",
            Self::AddFloat2addr => "add-float/2addr",
            Self::SubFloat2addr => "sub-float/2addr",
            Self::MulFloat2addr => "mul-float/2addr",
            Self::DivFloat2addr => "div-float/2addr",
            Self::RemFloat2addr => "rem-float/2addr",
            Self::AddDouble2addr => "add-double/2addr",
            Self::SubDouble2addr => "sub-double/2addr",
            Self::MulDouble2addr => "mul-double/2addr",
            Self::DivDouble2addr => "div-double/2addr",
            Self::RemDouble2addr => "rem-double/2addr",
            Self::AddIntLit16 => "add-int/lit16",
            Self::RsubInt => "rsub-int",
            Self::MulIntLit16 => "mul-int/lit16",
            Self::DivIntLit16 => "div-int/lit16",
            Self::RemIntLit16 => "rem-int/lit16",
            Self::AndIntLit16 => "and-int/lit16",
            Self::OrIntLit16 => "or-int/lit16",
            Self::XorIntLit16 => "xor-int/lit16",
            Self::AddIntLit8 => "add-int/lit8",
            Self::RsubIntLit8 => "rsub-int/lit8",
            Self::MulIntLit8 => "mul-int/lit8",
            Self::DivIntLit8 => "div-int/lit8",
            Self::RemIntLit8 => "rem-int/lit8",
            Self::AndIntLit8 => "and-int/lit8",
            Self::OrIntLit8 => "or-int/lit8",
            Self::XorIntLit8 => "xor-int/lit8",
            Self::ShlIntLit8 => "shl-int/lit8",
            Self::ShrIntLit8 => "shr-int/lit8",
            Self::UshrIntLit8 => "ushr-int/lit8",
            Self::IgetVolatile => "iget-volatile",
            Self::IputVolatile => "iput-volatile",
            Self::SgetVolatile => "sget-volatile",
            Self::SputVolatile => "sput-volatile",
            Self::IgetObjectVolatile => "iget-object-volatile",
            Self::IgetWideVolatile => "iget-wide-volatile",
            Self::IputWideVolatile => "iput-wide-volatile",
            Self::SgetWideVolatile => "sget-wide-volatile",
            Self::SputWideVolatile => "sput-wide-volatile",
            Self::ThrowVerificationError => "throw-verification-error",
            Self::ExecuteInline => "execute-inline",
            Self::ExecuteInlineRange => "execute-inline/range",
            Self::InvokeDirectEmpty => "invoke-direct-empty",
            Self::ReturnVoidBarrier => "return-void-barrier",
            Self::IgetQuick => "iget-quick",
            Self::IgetWideQuick => "iget-wide-quick",
            Self::IgetObjectQuick => "iget-object-quick",
            Self::IputQuick => "iput-quick",
            Self::IputWideQuick => "iput-wide-quick",
            Self::IputObjectQuick => "iput-object-quick",
            Self::InvokeVirtualQuick => "invoke-virtual-quick",
            Self::InvokeVirtualQuickRange => "invoke-virtual-quick/range",
            Self::InvokeSuperQuick => "invoke-super-quick",
            Self::InvokeSuperQuickRange => "invoke-super-quick/range",
            Self::IputObjectVolatile => "iput-object-volatile",
            Self::SgetObjectVolatile => "sget-object-volatile",
            Self::SputObjectVolatile => "sput-object-volatile",
            Self::ConstMethodType => "const-method-type",
        };
        write!(f, "{}", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_opcode_from_u8_all_defined() {
        let defined_opcodes: &[u8] = &[
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
            0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13,
            0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d,
            0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
            0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31,
            0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
            0x3c, 0x3d,
        ];
        for &byte in defined_opcodes {
            assert!(Opcode::from_u8(byte).is_some(), "opcode 0x{:02x} should be defined", byte);
        }
    }

    #[test]
    fn test_opcode_roundtrip() {
        for byte in 0u8..=0xFFu8 {
            if let Some(op) = Opcode::from_u8(byte) {
                assert_eq!(op as u8, byte, "roundtrip failed for 0x{:02x}", byte);
            }
        }
    }

    #[test]
    fn test_const_string_format() {
        assert_eq!(Opcode::ConstString.format(), InstructionFormat::Format21c);
        assert_eq!(Opcode::ConstString.code_units(), 2);
        assert_eq!(Opcode::ConstString.reference_type(), ReferenceType::String);
        assert!(Opcode::ConstString.can_throw());
    }

    #[test]
    fn test_const_string_jumbo_format() {
        assert_eq!(Opcode::ConstStringJumbo.format(), InstructionFormat::Format31c);
        assert_eq!(Opcode::ConstStringJumbo.code_units(), 3);
    }

    #[test]
    fn test_invoke_virtual_format() {
        assert_eq!(Opcode::InvokeVirtual.format(), InstructionFormat::Format35c);
        assert_eq!(Opcode::InvokeVirtual.code_units(), 3);
        assert_eq!(Opcode::InvokeVirtual.reference_type(), ReferenceType::Method);
    }

    #[test]
    fn test_return_void_format() {
        assert_eq!(Opcode::ReturnVoid.format(), InstructionFormat::Format10x);
        assert_eq!(Opcode::ReturnVoid.code_units(), 1);
    }

    #[test]
    fn test_nop_format() {
        assert_eq!(Opcode::Nop.format(), InstructionFormat::Format10x);
        assert_eq!(Opcode::Nop.code_units(), 1);
    }

    #[test]
    fn test_undefined_opcodes() {
        assert!(Opcode::from_u8(0x3e).is_none());
        assert!(Opcode::from_u8(0x3f).is_none());
        assert!(Opcode::from_u8(0x40).is_none());
        assert!(Opcode::from_u8(0x73).is_none());
        assert!(Opcode::from_u8(0x7a).is_none());
        assert!(Opcode::from_u8(0xEC).is_none());
    }

    #[test]
    fn test_opcode_display() {
        assert_eq!(Opcode::Nop.to_string(), "nop");
        assert_eq!(Opcode::ConstString.to_string(), "const-string");
        assert_eq!(Opcode::InvokeVirtual.to_string(), "invoke-virtual");
        assert_eq!(Opcode::ReturnVoid.to_string(), "return-void");
        assert_eq!(Opcode::AddIntLit8.to_string(), "add-int/lit8");
    }
}
